### ISSUE TITLE
It only works for HTTPs images?

### ISSUE THREAD

**Issue by casidiablo** [carolineartz/rendered_images_for_folding_text#2]
There's a bizarre behavior with FT and this plugin: it only shows the image if the URL starts with `https`. It makes no sense, and it's probably more of a FT bug, but I figured I'd bring it up here nonetheless.

**Comment by carolineartz** [comment]
@casidiablo Thanks for opening and commenting on folding text support forum. :) 

For posterity, I'll [link](http://support.hogbaysoftware.com/t/embedded-images-wont-load-unless-from-https/2094) and quote my forum response here. I've updated the plugin to work with both local file paths as well as hosted. :shipit: 

> This isn't a FoldingText bug per se, it's a feature. I believe it's the default security setting for OS X apps to to prevent insecure connections. So, in this case, Imgur provides both links and the https protocol will work, as you know. There is nothing appropriate I could implement to bypass this since it's there for a reason. I would simply use the secure link
